### ISSUE TITLE
AddDirRecursive panics when GOROOT is not set correctly

### ISSUE THREAD

**Issue by joelanford** [kubernetes/gengo#146]
It seems that when `GOROOT` is misconfigured, `Builder.AddDirRecursive` panics:

```
W0611 10:07:38.859903   39295 parse.go:224] Ignoring directory github.com/k8spatterns/hello-operator/pkg/apis: unable to import "github.com/k8spatterns/hello-operator/pkg/apis": go/build: importGo github.com/k8spatterns/hello-operator/pkg/apis: exit status 2
go: cannot find GOROOT directory: /usr/local/go

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1760595]

goroutine 1 [running]:
github.com/operator-framework/operator-sdk/vendor/k8s.io/gengo/parser.(*Builder).AddDirRecursive(0xc000962230, 0xc0006b71d0, 0x2e, 0x2, 0x2)
	src/github.com/operator-framework/operator-sdk/vendor/k8s.io/gengo/parser/parse.go:229 +0xb5
```

See https://github.com/operator-framework/operator-sdk/issues/1545 for more details.

**Comment by discordianfish** [comment]
Again a valid issue hitting people in the wild closed by this bot. @fejta Feedback: I don't like it.
