### ISSUE TITLE
segfault when running make, seems to come from gengo

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/gengo#43]
I get a segfault when I run make. I am rebased on latest upstream/master for k8s. This is not good.

Substituted private paths w/ PATHYMCPATHFACE:
```
$ make
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x45dcf2]

goroutine 1 [running]:
panic(0x692840, 0xc4200102e0)
	/PATHYMCPATHFACE/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kubernetes/vendor/k8s.io/gengo/examples/defaulter-gen/generators.getManualDefaultingFunctions(0xc430007a40, 0x0, 0xc4302989c0)
	/PATHYMCPATHFACE/go-tools/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go:113 +0x102
k8s.io/kubernetes/vendor/k8s.io/gengo/examples/defaulter-gen/generators.Packages(0xc430007a40, 0xc42001c680, 0x6db1d5, 0x6, 0xc430007a40)
	/PATHYMCPATHFACE/go-tools/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go:236 +0x6d2
k8s.io/kubernetes/vendor/k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc42001c680, 0xc420016fc0, 0x6db1d5, 0x6, 0x700988, 0x0, 0x0)
	/PATHYMCPATHFACE/go-tools/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/args/args.go:165 +0x170
main.main()
	/PATHYMCPATHFACE/go-tools/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/libs/go2idl/defaulter-gen/main.go:74 +0x1fb
make[1]: *** [gen_defaulter] Error 1
make: *** [generated_files] Error 2
```

**Comment by mtaufen** [comment]
Also occurs directly on upstream/master for me.

**Comment by mtaufen** [comment]
`make clean` fixed. Must have been corruption from an aborted build or something.

**Comment by mtaufen** [comment]
Reopening because this does mean that someone forgot to check a pointer somewhere...
